### PR TITLE
Allow to configure custom SFTP options

### PR DESCRIPTION
**Pull request by klausmeyer**
Hi 👋,

we've been using your nice gem for quite a while now and discovered the need to configure the options used to establish SFTP connections for downloading the identification files (e.g. whitelisting otherwise rejected host key algorithms).

Let me know what you think about that addition.

Thanks and best wishes,
Klaus

### CODE REVIEW

**Comment by klausmeyer** [comment]
Ping @rngtng 😁

**Comment by rngtng** [comment]
@klausmeyer sorry late response, was fully on different focus. thanks for your addition, LGTM

**Comment by klausmeyer** [comment]
Not a problem. Thanks for accepting the change 😁

**Comment by rngtng** [comment]
only gem release I'll do later sry

**Comment by klausmeyer** [comment]
Perfect. Thank you very much 👍

**Comment by klausmeyer** [comment]
@rngtng quick reminder on pushing a new version of this gem (whenever you have some spare minutes). Thanks :D

**Comment by rngtng** [comment]
done

**Comment by klausmeyer** [comment]
Many thanks ;)

**Pull request merged**
